### ISSUE TITLE
問い合わせフォームの一時的な無効化

### ISSUE THREAD

**Issue by tatsutakein** [ishinova/ishinova.co.jp#7]
### 同様の機能要望はございませんか？

- [x] 同様の機能要望はありませんでした。

### 1. **目的**
- 現状で `contactForm` のデータ送信機能は未実装であるため、誤送信やユーザーの混乱を防ぐ必要があります。
- 見た目としては、ユーザーが操作可能と誤解しない程度に「さりげなく」無効化状態を伝えるデザインにします。

---

#### **Step 1: フォーム全体の無効化**
1. **HTMLレベルでの無効化**
   - `form` タグやその内部の送信ボタン（`<button>`）に `disabled` 属性を追加します。
     ```html
     <form id="contactForm" action="#" method="post">
       <input type="text" placeholder="Your Name" disabled />
       <input type="email" placeholder="Your Email" disabled />
       <textarea placeholder="Your Message" disabled></textarea>
       <button type="submit" disabled>Send</button>
     </form>
     ```
   - `disabled` 属性を使うことで、ブラウザが自動的にユーザー操作を無効化します。

2. **JavaScriptでの保険的無効化**
   - フォームが JavaScript に依存する場合、送信イベントを防止するコードを追加します。
     ```javascript
     document.getElementById('contactForm').addEventListener('submit', function(event) {
       event.preventDefault(); // フォーム送信を防止
     });
     ```

---

#### **Step 2: 見た目の「さりげない」無効化デザイン**
1. **CSSでのスタイル調整**
   - 無効化されたフォーム要素が「薄暗く」または「グレーアウトされた」見た目になるように、CSSで以下のように設定します。
     ```css
     #contactForm input:disabled,
     #contactForm textarea:disabled,
     #contactForm button:disabled {
       background-color: #f5f5f5; /* 背景を薄い灰色に */
       color: #a5a5a5;           /* テキストを薄い色に */
       border: 1px solid #ccc;   /* 境界線を薄く */
       cursor: not-allowed;      /* カーソルを「禁止」に */
       opacity: 0.6;             /* 全体を少し透明に */
     }
     ```
   - 特にボタンは、押せないことが明示的に分かるよう、`cursor: not-allowed` を設定します。

2. **さりげない視覚効果**
   - フォーム全体に透明感を持たせることで、操作不可能であることを視覚的に示します。
     ```css
     #contactForm {
       opacity: 0.8; /* 全体を少し透明に */
       pointer-events: none; /* ユーザーの操作を完全に無効化 */
     }
     ```

---

#### **Step 3: 状態を動的に変更可能にする（将来の実装用に）**
- 今後データ送信機能が実装される場合に備え、`disabled` 状態を動的に切り替えられる設計を行います。
- フォームの有効化/無効化を JavaScript で制御します。
  ```javascript
  function toggleContactForm(isEnabled) {
    const formElements = document.querySelectorAll('#contactForm input, #contactForm textarea, #contactForm button');
    formElements.forEach(element => {
      element.disabled = !isEnabled; // true: 有効化, false: 無効化
    });
  }

  // デフォルトで無効化
  toggleContactForm(false);
  ```

---

### 3. **注意点**
- **アクセシビリティ**:
  - 無効化されたフォームの状態がスクリーンリーダーなどでも適切に伝わるように、`aria-disabled` 属性を追加します。
    ```html
    <form id="contactForm" aria-disabled="true">
    ```
- **ユーザーへのフィードバック**:
  - 無効化の理由を明確にするため、フォームの上部または下部に「現在このフォームは準備中です」といった小さなメッセージを追加することを検討します。
    ```html
    <p class="form-note">* This form is currently disabled and under development.</p>
    ```

---

### 4. **最終的なサンプルコード**
以下は、上記すべてを統合したサンプルコードです。

**HTML**
```html
<form id="contactForm" action="#" method="post" aria-disabled="true">
  <input type="text" placeholder="Your Name" disabled />
  <input type="email" placeholder="Your Email" disabled />
  <textarea placeholder="Your Message" disabled></textarea>
  <button type="submit" disabled>Send</button>
</form>
<p class="form-note">* This form is currently disabled and under development.</p>
```

**CSS**
```css
#contactForm input:disabled,
#contactForm textarea:disabled,
#contactForm button:disabled {
  background-color: #f5f5f5;
  color: #a5a5a5;
  border: 1px solid #ccc;
  cursor: not-allowed;
  opacity: 0.6;
}

#contactForm {
  opacity: 0.8;
  pointer-events: none;
}

.form-note {
  font-size: 0.9em;
  color: #888;
  margin-top: 10px;
}
```

**JavaScript**
```javascript
document.getElementById('contactForm').addEventListener('submit', function(event) {
  event.preventDefault(); // フォーム送信を防止
});

function toggleContactForm(isEnabled) {
  const formElements = document.querySelectorAll('#contactForm input, #contactForm textarea, #contactForm button');
  formElements.forEach(element => {
    element.disabled = !isEnabled;
  });
}

// デフォルトで無効化
toggleContactForm(false);
```

---

### 5. **ポイント**
- 無効化のデザインは「さりげなく」かつ「明確」に。
- 将来の機能拡張を考慮して柔軟性を持たせる。
- ユーザー体験を損なわないアクセシビリティを確保する。
